app = "fly-n8n-z2g57w"
primary_region = "cdg"

[deploy]
  release_command = ""

[env]
  GENERIC_TIMEZONE = "Europe/Paris"
  N8N_BASIC_AUTH_ACTIVE = "true"
  N8N_BASIC_AUTH_USER = "bisonrouge"
  N8N_BASIC_AUTH_PASSWORD = "mdp-n8n-12à98è12@K"
  N8N_PORT = "5678"
  N8N_HOST = "0.0.0.0"
  N8N_RUNNERS_ENABLED = "true"
  DB_SQLITE_VACUUM_ON_STARTUP = "true"

[[services]]
  internal_port = 5678
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443
    handlers = ["tls"]

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "10s"
    restart_limit = 0
