app = "fly-n8n-z2g57w"
primary_region = "cdg"

[build]
  image = "n8nio/n8n:latest"

[env]
  GENERIC_TIMEZONE            = "Europe/Paris"
  N8N_BASIC_AUTH_ACTIVE       = "true"
  N8N_BASIC_AUTH_USER         = "bisonrouge"
  # Supprime N8N_BASIC_AUTH_PASSWORD d’ici, il doit être en secret fly.io
  N8N_PORT                   = "5678"
  N8N_HOST                   = "0.0.0.0"
  N8N_RUNNERS_ENABLED         = "true"
  DB_SQLITE_VACUUM_ON_STARTUP = "true"

[[mounts]]
  source      = "n8n_vol"
  destination = "/home/node/.n8n"

[[services]]
  internal_port = 5678
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "10s"
    restart_limit = 0
