app = "fly-n8n-z2g57w"
primary_region = "cdg"

[http_service]
  internal_port = 5678
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[env]
  GENERIC_TIMEZONE = "Europe/Paris"
  N8N_BASIC_AUTH_ACTIVE = "true"
  N8N_BASIC_AUTH_USER = "bisonrouge"
  N8N_BASIC_AUTH_PASSWORD = "mdp-n8n-12à98è12@K"
  N8N_PORT = "5678"
  N8N_HOST = "0.0.0.0"
  N8N_RUNNERS_ENABLED = "true"
  DB_TYPE = "postgresdb"
  DB_POSTGRESDB_HOST = "db.uywaeaynlyciznbuszuz.supabase.co"
  DB_POSTGRESDB_PORT = "5432"
  DB_POSTGRESDB_DATABASE = "postgres"
  DB_POSTGRESDB_USER = "postgres"
  DB_POSTGRESDB_PASSWORD = "project-database-n8n-1"
  DB_POSTGRESDB_SSLMODE = "require"
