app = "fly-n8n-z2g57w"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 5678
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
  memory_mb = 1024

[[mounts]]
  source = "n8n_vol"
  destination = "/home/node/.n8n"

[env]
  GENERIC_TIMEZONE = "Europe/Paris"
  N8N_BASIC_AUTH_ACTIVE = "true"
  N8N_BASIC_AUTH_USER = "bisonrouge"
  N8N_BASIC_AUTH_PASSWORD = "mdp-n8n-12à98è12@K"
  N8N_PORT = "5678"
  N8N_HOST = "0.0.0.0"
  N8N_RUNNERS_ENABLED = "true"
  DB_SQLITE_VACUUM_ON_STARTUP = "true"
