# fly.toml app configuration file generated for fly-n8n-z2g57w on 2025-05-12T11:37:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-n8n-z2g57w'
primary_region = 'cdg'

[build]

[http_service]
internal_port       = 5678
force_https         = true
auto_stop_machines  = "never"
auto_start_machines = true
min_machines_running = 1
processes           = ["app"]


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
  
[env]
  N8N_PORT = "8080"

