app = "fly-n8n-z2g57w"
primary_region = "cdg"

[build]

[http_service]
  internal_port       = 5678
  force_https         = true
  auto_stop_machines  = "never"
  auto_start_machines = true
  min_machines_running = 1
  processes           = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus     = 1
  memory   = "1gb"
  memory_mb = 1024

[env]
  # Fuseau horaire
  GENERIC_TIMEZONE = "Europe/Paris"
  # Auth basique
  N8N_BASIC_AUTH_ACTIVE   = "true"
  N8N_BASIC_AUTH_USER     = "bisonrouge"
  N8N_BASIC_AUTH_PASSWORD = "mdp-n8n-12à98è12@K"
  # Ports et hôte
  N8N_PORT = "5678"
  N8N_HOST = "0.0.0.0"
  # Activer les task runners
  N8N_RUNNERS_ENABLED = "true"
  # Compaction SQLite au démarrage
  DB_SQLITE_VACUUM_ON_STARTUP = "true"

[[mounts]]
  source      = "n8n_vol"
  destination = "/home/node/.n8n"
